query BasketQuery($after: String, $id: ID) {
	basket(id: $id) {
		books(after: $after, first: 10) {
			edges {
				node @required {
					id
				}
				quantity
				...Summable_edge
			}
			pageInfo {
				endCursor
				hasNextPage
			}
		}
		id
		price {
			formatted
		}
	}
	viewer {
		id
	}
}
