query PurchasesQuery($after: String, $before: String, $first: Int, $id: ID!, $last: Int) {
	node(id: $id) {
		... on User {
			id
			purchases(after: $after, before: $before, first: $first, last: $last) {
				edges {
					node {
						createdAt
						databaseId
						id
						price {
							formatted
						}
						status
					}
				}
				pageInfo {
					...Pagination_pageInfo
				}
			}
		}
	}
}
