query NavbarQuery($id: ID) {
	basket(id: $id) {
		id
		price {
			formatted
		}
		quantity
	}
	viewer {
		__typename
		id
		purchases(first: 10, where: { status: MADE }) {
			edges {
				__typename
			}
			pageInfo {
				hasNextPage
			}
		}
		... on User {
			__typename
		}
		... on Admin {
			__typename
		}
	}
}
