query PurchaseQuery($id: ID!) {
	node(id: $id) {
		id
		... on Purchase {
			books(first: 10) {
				edges {
					node @required {
						id
					}
					...Summable_edge
				}
				pageInfo {
					...Pagination_pageInfo
				}
			}
			createdAt
			id
			payUrl
			price {
				formatted
			}
			status
		}
	}
	viewer {
		__typename
		id
	}
}
